Fix need absolute firewall path for CentOS 7
carlocorradini/node_exporter_installer pull request #37
Opened 2023-01-02 13:15 UTC by deajan

Been playing around a bit with your script lately.
Noticed this error on CentOS 7 where `firewall-cmd` full path seems mandatory:

Steps to reproduce:

1. Install CentOS Linux release 7.9.2009 (Core)
2. Execute current `install.sh` script
3. Run `journalctl -u node_exporter` to check why `node_exporter.service` fails

```
Jan 02 12:57:27 some.system.tld systemd[1]: [/etc/systemd/system/node_exporter.service:23] Executable path is not absolute, ignoring: firewall-cmd --add-port=9100/tcp --permanent
Jan 02 12:57:27 some.system.tld systemd[1]: [/etc/systemd/system/node_exporter.service:24] Executable path is not absolute, ignoring: firewall-cmd --reload
```

This patch replaces firewall binary with full path to firewall binary.

2023-01-02 13:24 UTC, deajan commented
Sorry, I cannot be bothered to rewrie my commits to behave for commit messages in your linter, too much burden for a single script.

2023-01-02 16:48 UTC, carlocorradini requested changes

2023-01-02 16:48 UTC, carlocorradini commented on install.sh
> +      FIREWALL=$(command -v "$_cmd" 2>/dev/null)
Remove.
I prefer `FIREWALL` to remain the simple name (as `DOWNLOADER`) and not the full path.

2023-01-02 16:48 UTC, carlocorradini commented on install.sh
>  firewall_rule() {
I prefer this:
```sh
# Compose firewall rule
firewall_rule() {
  _firewall_path=$(command -v "$FIREWALL" 2>&1 || :)

  case $FIREWALL in
    firewall-cmd)
      printf "%s\n%s\n" \
        "$_firewall_path --add-port=$NODE_EXPORTER_PORT/tcp --permanent" \
        "$_firewall_path --reload"
      ;;
    ufw)
      printf "%s\n" \
        "$_firewall_path allow $NODE_EXPORTER_PORT/tcp"
      ;;
    iptables)
      printf "%s\n" \
        "$_firewall_path -A INPUT -p tcp --dport $NODE_EXPORTER_PORT -m state --state NEW -j ACCEPT"
      ;;
    *) fatal "Unknown firewall '$FIREWALL'" ;;
  esac
}
```

Note: `firewall_rule` is called only if a firewall exists. `|| :` and `*) fatal ...` are only for correctness.

2023-01-02 16:49 UTC, carlocorradini commented
Nice catch!

2023-01-03 10:03 UTC, carlocorradini approved these changes

2023-01-03 10:04 UTC, merged